### ISSUE TITLE
Rust stable

### ISSUE THREAD

**Issue by aptakhin** [goffrie/plex#13]
Hi!

I'm not very familiar with Rust, but very excited by your library. Only my problem is I decided to keep on latest stable Rust.
Is it very difficult to support stable Rust at least lexer part?

**Comment by goffrie** [comment]
Hi! It should be possible, but I'm not currently working on it. I'm not very happy with the current options for stable, so I'm going to wait a little at least.

**Comment by sakshamsharma** [comment]
Hi, what's the status on this issue again?
Also, what rust version are you building on? I just encountered a significant number of errors on `cargo build`'s compilation of `plex`. I'm on Gentoo's nightly branch of rust.

**Comment by goffrie** [comment]
Hi! I'm pretty busy at the moment, so I haven't been actively keeping up to
date with Rust master. I'd accept a pull request that works against nightly
though ;)

As for stable support... I'd prefer to wait until procedural macros are
properly supported in stable, rather than porting it to the syntex/build
script approach, which I'm not a fan of.

**Comment by sakshamsharma** [comment]
Thanks for the quick reply!
I'm just starting with rust right now, so perhaps this may be beyond me. But I can try.

**Comment by kivikakk** [comment]
I'm having a look at this now, too. Mostly it just seems to be renaming and some minor reworks of syntax.

**Comment by sakshamsharma** [comment]
I tried it too. Isn't straightforward, since one function/enum now requires
u128 type, which is unstable, and doesn't compile. At another point, a
function now requires a new argument (Span), which I did not understand. Do
let me know if you can make this work. I need this urgently myself. Thanks
:smile:

**Comment by kivikakk** [comment]
Down to 5 compile errors (from ~50), so I'll let you know if I get there! 😸

**Comment by kivikakk** [comment]
Oh, damn. I wasn't working on the latest master. -_- I'll be a little bit more.

**Comment by kivikakk** [comment]
Turns out I redid a lot of work. PR incoming.

**Comment by sakshamsharma** [comment]
Great! I'll test it out soon. Although, are you informed enough to be able to port it to stable? (In case you would prefer that as well). There's this library [rustlex](https://github.com/LeoTestard/rustlex) which works on both. Perhaps something like that can be made for this, if possible? I'm quite new to rust, and low on time, so cannot make that work right now. No hurry though :smile:

**Comment by kivikakk** [comment]
Unfortunately not; I'm very advanced at Rust either, and I do think it would be a biiiig effort to port this; better waiting for the features to come to stable (or ideally, target nightly yourself).

**Comment by sakshamsharma** [comment]
I wouldn't target a nightly build I'm afraid. But is it safe to assume (from, for instance, [here](https://www.reddit.com/r/rust/comments/5k4sep/a_tale_of_two_rusts/) ) that macros 1.1 should be in stable within a week or two? That's what is holding back plex from building on stable, right?

**Comment by longwusha** [comment]
Has anybody built successfully with a stable version compiler?

**Comment by kaimast** [comment]
> Has anybody built successfully with a stable version compiler?

As long as the procedural macros aren't stabilized yet, I don't think you can build this crate with stable (or even beta).

See this issue for more info: https://github.com/rust-lang/rust/issues/54725

**Comment by maxrdz** [comment]
I see that [rust-lang/rust#54725](https://github.com/rust-lang/rust/issues/54725) is still in nightly and under active development to this day. Since the last activity in this repository was in 2020, I wanted to ask if the maintainers are still looking to update this crate once this feature is on rust stable?

**Comment by goffrie** [comment]
I ported the crate to use syn 2.0.0 and compile_error!-style error reporting (using syn::Error) in fafa4dcdbd51dd4f0c7fba58109842a0481fd05d. With that, the crate now compiles on stable.

**Comment by maxrdz** [comment]
Thank you! 😊

**Comment by maxrdz** [comment]
Would it be possible to make a new release with this feature? Would be great if I can build my project with the latest version of the crate without needing to compile from source. Thank you :)

**Comment by ErikBjare** [comment]
@maxrdz v0.3 was just released!

**Comment by maxrdz** [comment]
Sweet, thanks for letting me know!On Oct 28, 2023, at 4:57 AM, Erik Bjäreholt ***@***.***> wrote:﻿
@maxrdz v0.3 was just released!
